apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-proshop-secret
type: Opaque
stringData:
  mongo-uri: {{ required "MongoDB URI is required" .Values.secret.mongoUri | quote }}
  jwt-secret: {{ required "JWT secret is required" .Values.secret.jwtSecret | quote }}